version: '3'

services:
  auth:
    build: ./microservices/auth
    ports:
      - "50052:50052"
    networks:
      - microservices

  users:
    build: ./microservices/users
    ports:
      - "50053:50053"
    networks:
      - microservices

  logs:
    build: ./microservices/logs
    ports:
      - "50054:50054"
    networks:
      - microservices

  products:
    build: ./microservices/products
    ports:
      - "50055:50055"
    networks:
      - microservices

  orders:
    build: ./microservices/orders
    ports:
      - "50056:50056"
    networks:
      - microservices

  payments:
    build: ./microservices/payments
    ports:
      - "50057:50057"
    networks:
      - microservices
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - microservices
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - microservices
networks:
  microservices:
    driver: bridge